[package]
name = "ricex"
version = "0.1.0"
authors = ["Alex Kane <wkanew@yahoo.co.nz>"]

[dependencies]
palette = "0.2.1"
byteorder = "0.4.2"
stopwatch = "0.0.6"
kiss-ui = { git = "https://github.com/KISS-UI/kiss-ui"}
